#Welcome to Jekyll!

#Site settings
title: Pare and Flourish
description: Another short description for a website I absolutely hate writing these.. skylar, you're up.
owner: Pare and Flourish #Company name.
first_published: 2016 
email: your-email@domain.com
baseurl: ""
url: ""
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Navigation
defaults:
  - scope:
      path: _posts
      type: blog
    values:
      layout: pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: pages